const products = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    rating: {
      rate: 4.75,
      count: 850,
    },
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    rating: {
      rate: 4.43,
      count: 254,
    },
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    rating: {
      rate: 4.4,
      count: 354,
    },
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
  },
  {
    id: 4,
    title: "OPPO F19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    rating: {
      rate: 4.3,
      count: 540,
    },
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
  },
  {
    id: 5,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    rating: {
      rate: 4.09,
      count: 125,
    },
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
  },
  {
    id: 6,
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    rating: {
      rate: 4.6,
      count: 222,
    },
    stock: 83,
    brand: "Apple",
    category: "laptop",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: [
      "https://i.dummyjson.com/data/products/6/1.png",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    rating: 4.25,
    rating: {
      rate: 4.25,
      count: 352,
    },
    stock: 50,
    brand: "Samsung",
    category: "laptop",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/7/1.jpg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
      "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    ],
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    rating: {
      rate: 4.43,
      count: 300,
    },
    stock: 68,
    brand: "Microsoft",
    category: "laptop",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
  },
  {
    id: 9,
    title: "Infinix INBOOK X1 Pro laptop",
    description:
      "Infinix Inbook X1 Core i3, 10th gen, 8GB Ram, 256GB SSD, 14 inch FHD display, Windows 10, color: Grey, with 1 Year Warranty",
    price: 1099,
    rating: {
      rate: 4.54,
      count: 150,
    },
    stock: 96,
    brand: "Infinix",
    category: "laptop",
    thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/9/1.jpg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
      "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    ],
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM laptop",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    rating: {
      rate: 4.43,
      count: 203,
    },
    stock: 89,
    brand: "HP",
    category: "laptop",
    thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    images: [
      "https://i.dummyjson.com/data/products/10/1.jpg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
      "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    ],
  },
  {
    id: 11,
    title: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
    price: 64,
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    rating: {
      rate: 3.3,
      count: 203,
    },
    stock: 58,
    brand: "Western Digital",
    category: "storage",
    thumbnail: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
  },
  {
    id: 12,
    title: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    price: 109,
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "storage",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    rating: {
      rate: 2.9,
      count: 470,
    },
    stock: 25,
    brand: "SanDisk",
  },
  {
    id: 13,
    title:
      "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    price: 109,
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "storage",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    rating: {
      rate: 4.8,
      count: 319,
    },
    stock: 12,
    brand: "Silicon Power",
  },
  {
    id: 14,
    title:
      "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    price: 114,
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "storage",
    brand: "Western Digital",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    rating: {
      rate: 4.8,
      count: 400,
    },
    stock: 20,
  },
  {
    id: 15,
    title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    price: 599,
    description:
      "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    category: "monitor",
    brand: "Acer",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    rating: {
      rate: 2.9,
      count: 250,
    },
    stock: 12,
  },
  {
    id: 16,
    title: "Samsung 49 Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA)",
    price: 999.99,
    description:
      "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    category: "monitor",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    rating: {
      rate: 2.2,
      count: 140,
    },
    stock: 15,
    brand: "Samsung",
  },
  {
    id: 9001,
    title: "Acer Nitro 5 AN515-57-79TD Gaming Laptop",
    price: 739.99,
    oldPrice: 1000.99,
    description:
      "Acer Nitro 5 AN515-57-79TD Gaming Laptop | Intel Core i7-11800H | NVIDIA GeForce RTX 3050 Ti Laptop GPU | 15.6 FHD 144Hz IPS Display | 8GB DDR4 | 512GB NVMe SSD | Killer Wi-Fi 6 | Backlit Keyboard",
    category: "laptop",
    image: "https://i.ibb.co/jTMbP5r/nextamazon1.jpg",
    isNew: true,
    brand: "Acer",
    rating: {
      rate: 3.85,
      count: 85,
    },
    stock: 9,
  },
  {
    id: 9002,
    title: "Acer Aspire 5 A515-45-R74Z Slim Laptop",
    price: 399.99,
    oldPrice: 599.45,
    description:
      "Acer Aspire 5 A515-45-R74Z Slim Laptop | 15.6 Full HD IPS | AMD Ryzen 5 5500U Hexa-Core Mobile Processor | AMD Radeon Graphics | 8GB DDR4 | 256GB NVMe SSD | WiFi 6 | Backlit KB | Windows 11 Home",
    category: "laptop",
    image: "https://i.ibb.co/2vwS6HR/nextamazon2.jpg",
    isNew: true,
    brand: "Acer",
    rating: {
      rate: 4.85,
      count: 45,
    },
    stock: 19,
  },
  {
    id: 9003,
    title: "2020 Apple iPad Pro",
    price: 747.07,
    oldPrice: 850.99,
    description:
      "2020 Apple iPad Pro (12.9-inch, Wi-Fi, 256GB) - Space Gray (Renewed)",
    category: "smartphones",
    image: "https://i.ibb.co/SybqWjf/nextamazon3.jpg",
    isNew: true,
    brand: "Apple",
    rating: {
      rate: 4.58,
      count: 152,
    },
    stock: 45,
  },
  {
    id: 9004,
    title: "Garmin Smart Watches for Men",
    price: 56.99,
    oldPrice: 65.85,
    description:
      "Garmin Smart Watches for Men (Answer/Make Call) 100 Sport Modes Fitness Tracker Heart Rate Blood Oxygen Sleep Monitor IP68 Waterproof Fitness Watch Activity Tracker and Smartwatches iPhone Android Compatible",
    category: "watch",
    image: "https://i.ibb.co/0Gvx3Sk/nextImg.jpg",
    isNew: true,
    brand: "Garmin",
    rating: {
      rate: 4.25,
      count: 95,
    },
    stock: 65,
  },
  {
    id: 9005,
    title: "HP 24 Inch Computer Monitor -FHD 1080P Gaming Monitor",
    price: 118.9,
    oldPrice: 180.58,
    description:
      "HP 24 Inch Computer Monitor -FHD 1080P Gaming Monitor 165Hz VA 1ms Build-in FreeSync™, Compatible G-sync, LED Monitors with Ultra-Thin, HDMI X2 /DP, VESA Compatible, Tilt Adjustable, Eye Care 24E4",
    category: "monitor",
    image: "https://i.ibb.co/xD7nDq5/nextamazon5.jpg",
    isNew: false,
    brand: "HP",
    rating: {
      rate: 4.88,
      count: 453,
    },
    stock: 25,
  },
  {
    id: 9006,
    title: "HP Mini PC Window 11 Pro",
    price: 338,
    oldPrice: 450,
    description:
      "HP Mini PC Window 11 Pro, AMD Ryzen 7 3750H Micro Desktop Computers 16GB DDR4 512GB PCIe SSD, 4K UHD Triple Screen Mini Computer for Light Gaming Business Office Video Editing",
    category: "computer",
    image: "https://i.ibb.co/pv6ZG1b/nextamazon6.jpg",
    isNew: true,
    brand: "HP",
    rating: {
      rate: 4.2,
      count: 401,
    },
    stock: 142,
  },
  {
    id: 9007,
    title: "Dell Gaming PC Desktop Computer Intel i7",
    price: 499.99,
    oldPrice: 520.5,
    description:
      "Dell Gaming PC Desktop Computer Intel i7 3.40GHz,16GB Ram,1TB Hard Drive,Windows 10 pro,WiFi Ready,Video Card Nvidia GTX 750 4GB, 6 RGB Fans with Remote",
    category: "computer",
    image: "https://i.ibb.co/9HPcTJv/nextamazon7.jpg",
    isNew: true,
    brand: "Dell",
    rating: {
      rate: 4.45,
      count: 350,
    },
    stock: 124,
  },
  {
    id: 9008,
    title: "HP Shadow 3.0 Gaming Computer PC",
    price: 899.99,
    oldPrice: 950,
    description:
      "HP Shadow 3.0 Gaming Computer PC Desktop - Ryzen 5 3600 6-Core 3.6GHz, GTX 1660 Super 6G, 1TB SSD, 16GB DDR4 3000, AC WiFi, Windows 10 Home 64-bit, Black",
    category: "computer",
    image: "https://i.ibb.co/DYmhxf8/nextamazon8.jpg",
    isNew: true,
    brand: "HP",
    rating: {
      rate: 4.88,
      count: 410,
    },
    stock: 124,
  },
  {
    id: 9009,
    title: "DJI Crusher Evo Wireless Over-Ear Bluetooth Headphones",
    price: 147.9,
    oldPrice: 190.5,
    description:
      "DJI Crusher Evo Wireless Over-Ear Bluetooth Headphones for iPhone and Android with Mic / 40 Hour Battery Life / Extra Bass Tech / Best for Music, School, Workouts, and Gaming - Black",
    category: "sound-system",
    image: "https://i.ibb.co/ZG9t4RL/nextamazon9.jpg",
    isNew: true,
    brand: "DJI",
    rating: {
      rate: 4.42,
      count: 245,
    },
    stock: 42,
  },
  {
    id: 9010,
    title: "Garmin 010-02430-01 Venu 2",
    price: 319.98,
    oldPrice: 450.5,
    description:
      "Garmin 010-02430-01 Venu 2, GPS Smartwatch with Advanced Health Monitoring and Fitness Features, Slate Bezel with Black Case and Silicone Band",
    category: "watch",
    image: "https://i.ibb.co/z7yV4zf/nextamazon10.jpg",
    isNew: true,
    brand: "Garmin",
    rating: {
      rate: 4.05,
      count: 120,
    },
    stock: 25,
  },
  {
    id: 9011,
    title: "Canon EOS Rebel T100",
    description:
      "Canon EOS Rebel T100 Digital SLR Camera with 18-55mm Lens Kit, 18 Megapixel Sensor, Wi-Fi, DIGIC4+, SanDisk 32GB Memory Card and Live View Shooting",
    price: 559.99,
    oldPrice: 700,
    image: "https://i.ibb.co/1r28gMk/1.webp",
    isNew: true,
    category: "camera",
    brand: "Canon",
    rating: {
      rate: 4.86,
      count: 650,
    },
    stock: 130,
  },
  {
    id: 9012,
    title: "DJI Air",
    description:
      "DJI Mini 2 Fly More Combo - Ultralight Foldable Drone, 3-Axis Gimbal with 4K Camera, 12MP Photos, 31 Min Flight Time",
    oldPrice: 1050,
    price: 999,
    brand: "DJI",
    image: "https://i.ibb.co/qdfB3s6/2.webp",
    isNew: true,
    category: "camera",
    rating: {
      rate: 4.88,
      count: 453,
    },
    stock: 25,
  },
  {
    id: 9013,
    title: "Apple 10.2-inch iPad",
    description:
      "2021 Apple 10.2-inch iPad Wi-Fi 64GB - Space Gray (9th Generation)",
    oldPrice: 329,
    price: 269,
    image: "https://i.ibb.co/VL1Dnv1/4.webp",
    isNew: true,
    category: "smartphones",
    brand: "Apple",
    rating: {
      rate: 4.42,
      count: 750,
    },
    stock: 31,
  },
  {
    id: 9014,
    title: "iPhone 14",
    description: "AT&T iPhone 14 128GB Midnight",
    oldPrice: 1745.99,
    price: 1200,
    image: "https://i.ibb.co/5F3nWv6/7.webp",
    isNew: true,
    category: "smartphones",
    brand: "Apple",
    rating: {
      rate: 4.9,
      count: 458,
    },
    stock: 85,
  },
  {
    id: 9015,
    title: "Apple Watch SE",
    description:
      "Apple Watch SE (2nd Gen) GPS 40mm Midnight Aluminum Case with Midnight Sport Band - S/M",
    price: 249,
    oldPrice: 350,
    image: "https://i.ibb.co/xgZWmdq/8.jpg",
    isNew: true,
    category: "watch",
    brand: "Apple",
    rating: {
      rate: 4.5,
      count: 350,
    },
    stock: 120,
  },
  {
    id: 9016,
    title: "Beats Solo 3",
    description:
      "Beats Solo3 Wireless On-Ear Headphones with Apple W1 Headphone Chip, Black, MX432LL/A",
    oldPrice: 120.99,
    price: 130.09,
    image: "https://i.ibb.co/rQKjVC2/5.webp",
    isNew: true,
    category: "sound-system",
    brand: "Beats",
    rating: {
      rate: 4.22,
      count: 120,
    },
    stock: 30,
  },
  {
    id: 9018,
    title: "DJI Smart Watch",
    description:
      "DJI Smart Watch, 1.7inchs Fitness Tracker with Heart Rate Monitor,Blood Oxygen Tracking, Sleep Tracking for Android iPhone Samsung,Water Resistant Smart Watches for Men Women with Watch Talking",
    oldPrice: 49.99,
    price: 55.9,
    image: "https://i.ibb.co/VC2VWGL/nextamazon11.jpg",
    isNew: true,
    category: "watch",
    brand: "DJI",
    rating: {
      rate: 4.12,
      count: 120,
    },
    stock: 10,
  },
  {
    id: 9019,
    title: "SAMSUNG Galaxy S23 Ultra Cell Phone",
    description:
      "SAMSUNG Galaxy S23 Ultra Cell Phone, Factory Unlocked Android smartphones, 512GB Storage, 200MP Camera, Night Mode, Long Battery Life, S Pen, US Version, 2023, Cream",
    oldPrice: 1279.99,
    price: 1500,
    image: "https://i.ibb.co/THwjSTK/nextamazon12.jpg",
    isNew: true,
    category: "smartphones",
    brand: "SAMSUNG",
    rating: {
      rate: 4.8,
      count: 680,
    },
    stock: 120,
  },
  {
    id: 9020,
    title: "Apple iPhone 12 Mini 5G",
    description:
      "Apple iPhone 12 Mini 5G, US Version, 128GB, Blue - Unlocked (Renewed)",
    oldPrice: 344,
    price: 365,
    image: "https://i.ibb.co/nry7WRZ/nextamazon13.jpg",
    isNew: true,
    category: "smartphones",
    brand: "Apple",
    rating: {
      rate: 4.8,
      count: 1200,
    },
    stock: 120,
  },
];

module.exports = { products };
